---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: ./test/fixtures/data_bags

platforms:
  - name: centos-6.6

suites:
  - name: default
    run_list:
     - recipe[workflow_apache_support::default]
     - recipe[workflow_apache_support::docroot]
     - recipe[workflow_apache_support::homepage]
    attributes:
      apache: 
        docroot: "/htdocs"
